DROP TABLE IF EXISTS COMMENT;

CREATE TABLE COMMENT (
ID BIGSERIAL NOT NULL CONSTRAINT PK_COMMENT PRIMARY KEY,
BODY VARCHAR (255) NOT NULL UNIQUE,
COMMENT_DATE TIMESTAMP NOT NULL,
BOOK_ID BIGINT NOT NULL
);