spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: subscription_catalog
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  batch:
    job:
      enabled: false