DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
ID BIGSERIAL NOT NULL CONSTRAINT PK_USERS PRIMARY KEY,
USERNAME VARCHAR (255) NOT NULL UNIQUE,
PASSWORD VARCHAR (255) NOT NULL,
EMAIL VARCHAR (255) NOT NULL
);

DROP TABLE IF EXISTS SUBSCRIPTIONS CASCADE;

CREATE TABLE SUBSCRIPTIONS (
ID BIGSERIAL NOT NULL CONSTRAINT PK_SUBSCRIPTIONS PRIMARY KEY,
STARTED_AT TIMESTAMP,
ENDED_AT TIMESTAMP,
PRICE DECIMAL,
NOTIFY_TIME TIMESTAMP,
USER_ID BIGINT NOT NULL CONSTRAINT FK_USERS REFERENCES USERS
);

DROP TABLE IF EXISTS SERVICES CASCADE;

CREATE TABLE SERVICES (
ID BIGSERIAL NOT NULL CONSTRAINT PK_SERVICES PRIMARY KEY,
NAME VARCHAR (255) NOT NULL UNIQUE,
LINK VARCHAR (255) NOT NULL,
FAVICON VARCHAR (255) NOT NULL,
SUBSCRIPTION_ID BIGINT NOT NULL CONSTRAINT FK_SUBSCRIPTIONS REFERENCES SUBSCRIPTIONS
);

DROP TABLE IF EXISTS CATEGORIES CASCADE;

CREATE TABLE CATEGORIES (
ID BIGSERIAL NOT NULL CONSTRAINT PK_CATEGORIES PRIMARY KEY,
NAME VARCHAR (255) NOT NULL UNIQUE,
SERVICE_ID BIGINT NOT NULL CONSTRAINT FK_SERVICES REFERENCES CATEGORIES
);