DROP TABLE IF EXISTS AUTHOR CASCADE;

CREATE TABLE AUTHOR (
ID BIGSERIAL NOT NULL CONSTRAINT PK_AUTHOR PRIMARY KEY,
NAME VARCHAR (255) NOT NULL,
SURNAME VARCHAR (255) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
UNIQUE(NAME, SURNAME, DATE_OF_BIRTH)
);

DROP TABLE IF EXISTS GENRE CASCADE;

CREATE TABLE GENRE (
ID BIGSERIAL NOT NULL CONSTRAINT PK_GENRE PRIMARY KEY,
NAME VARCHAR(100) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOK CASCADE;

CREATE TABLE BOOK (
ID BIGSERIAL NOT NULL CONSTRAINT PK_BOOK PRIMARY KEY,
TITLE VARCHAR (255) NOT NULL UNIQUE,
GENRE_ID BIGINT NOT NULL CONSTRAINT FK_GENRE REFERENCES GENRE
);

DROP TABLE IF EXISTS BOOK_AUTHOR;

CREATE TABLE BOOK_AUTHOR (
ID BIGSERIAL NOT NULL CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY,
AUTHOR_ID BIGINT NOT NULL CONSTRAINT FK_AUTHOR REFERENCES AUTHOR ON DELETE CASCADE,
BOOK_ID BIGINT NOT NULL CONSTRAINT FK_BOOK REFERENCES BOOK ON DELETE CASCADE
);