server:
  port: 8081

eureka:
  client:
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

spring:
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true