version: "3.7"

services:
  app:
    build: .
    image: app_image
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017